### ISSUE TITLE
pycodestylerc ignored

### ISSUE THREAD

**Issue by matt-chan** [theochem/cardboardlint#70]
The max line length option in pycodestylerc is being ignored. It still uses 80 regardless of what you put. For an example, see the entry in cellcutoffs.

**Comment by tovrstra** [comment]
This is due to the way pycodestyle looks for config files, which isn't cardboardlint's fault. I'll make PRs to fix this.

**Comment by tovrstra** [comment]
I've checked all projects in theochem and made corresponding PRs.
