### ISSUE TITLE
Add Python coverage linter

### ISSUE THREAD

**Issue by tovrstra** [theochem/cardboardlint#8]
See https://github.com/theochem/horton/blob/master/tools/qa/trapdoor_coverage.py

**Comment by tovrstra** [comment]
Best to give it a python-specific name.

**Comment by tovrstra** [comment]
@matt-chan coverage may not be suitable for our cardboard linter because the lines missed by tests may be very different from the lines changed in the diff. I think codecov is going to be a better solution for this: https://codecov.io

**Comment by matt-chan** [comment]
Yeah, let's go with codecov for that. So we'll put it directly into our travis/buildkite scripts, not into cardboardlint.
